### ISSUE TITLE
Issues updating pipeline activities

### ISSUE THREAD

**Issue by tomhobson** [jenkins-x-plugins/jx-build-controller#32]
Our pipeline activities are in a pending state:
```
jx          my-org-document-recogniser-master-2         https://github.com/my-org/document-recogniser.git         Succeeded
jx          my-org-document-recogniser-master-3         https://github.com/my-org/document-recogniser.git         Succeeded
jx          my-org-document-recogniser-master-4         https://github.com/my-org/document-recogniser.git         Succeeded
jx          my-org-document-recogniser-master-5         https://github.com/my-org/document-recogniser.git         Succeeded
jx          my-org-document-recogniser-master-6         https://github.com/my-org/document-recogniser.git         Failed
jx          my-org-document-recogniser-master-7                                                                                         
jx          my-org-document-recogniser-pr-123-1         https://github.com/my-org/document-recogniser.git         Succeeded
jx          my-org-document-recogniser-pr-123-19        https://github.com/my-org/document-recogniser.git         Pending
jx          my-org-document-recogniser-pr-123-2         https://github.com/my-org/document-recogniser.git         Failed
jx          my-org-document-recogniser-pr-123-20        https://github.com/my-org/document-recogniser.git         Pending
jx          my-org-document-recogniser-pr-123-21        https://github.com/my-org/document-recogniser.git         Pending
jx          my-org-document-recogniser-pr-123-4         https://github.com/my-org/document-recogniser.git         Succeeded
jx          my-org-document-recogniser-pr-123-5         https://github.com/my-org/document-recogniser.git         Failed
jx          my-org-document-recogniser-pr-123-6         https://github.com/my-org/document-recogniser.git         Pending
jx          my-org-document-recogniser-pr-123-9         https://github.com/my-org/document-recogniser.git         Running
jx          my-org-document-recogniser-pr-125-1         https://github.com/my-org/document-recogniser.git         Failed
jx          my-org-document-recogniser-pr-125-2         https://github.com/my-org/document-recogniser.git         Failed
jx          my-org-document-recogniser-pr-126-1         https://github.com/my-org/document-recogniser.git         Pending
jx          my-org-document-recogniser-pr-127-1         https://github.com/my-org/document-recogniser.git         Pending
```

I spoke to @vbehar and he told me to raise an issue here. 

he also pointed me to the jx build controller and I found this log here:

```{"level":"warning","msg":"failed to process PipelineRun pr-ldrnf in namespace jx: failed to update PipelineActivity  after 5 attempts: failed to update PipelineActivity my-org-document-recogniser-pr-123-20 in namespace jx: PipelineActivity.jenkins.io \"my-org-document-recogniser-pr-123-20\" is invalid: spec.steps.stage.steps.startedTimestamp: Invalid value: \"null\": spec.steps.stage.steps.startedTimestamp in body must be of type string: \"null\"","time":"2021-06-18T09:12:21Z"```

Here's our PR pipeline

```
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  creationTimestamp: null
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          image: uses:jenkins-x/jx3-pipeline-catalog/tasks/python/pullrequest.yaml@versionStream
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 1Gi
          workingDir: /workspace/source
        steps:
        - image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream
          name: ""
          resources: {}
        - name: jx-variables
          resources: {}
        - name: check-registry
          resources: {}
        - name: build-container-build
          resources: {}
        - image: ghcr.io/jenkins-x-plugins/jx-preview:0.0.143
          name: promote-jx-preview
          resources: {}
          script: |
            #!/usr/bin/env sh 
            source .jx/variables.sh
            jx secret copy --create-namespace --selector "secret.jenkins-x.io/replica-source=true" -n preview-secrets --to jx-$REPO_OWNER-$APP_NAME-pr-$PULL_NUMBER
            jx preview create
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 1h0m0s
status: {}
```

Not sure what's happening here. I'm going to look into it and I'll update the issue if I get anywhere
