### ISSUE TITLE
Logs not uploaded

### ISSUE THREAD

**Issue by chrislovecnm** [jenkins-x-plugins/jx-build-controller#55]
## Problem

I have recently installed jx3 in AWS EKS using and existing cluster and the TF provider in your instructions.  When a build runs the logs are not accessible or stored in s3. I go into dashboard and attempt to access the raw logs and get this error:

```
failed to read key jenkins-x/logs/REDACTED/jenkinsx-node-quickstart/PR-3/2.log in bucket s3://logs-REDACTED-20220420182851392800000001: blob (key "jenkins-x/logs/sREDACTED/jenkinsx-node-quickstart/PR-3/2.log") (code=NotFound): NoSuchKey: The specified key does not exist.
	status code: 404, request id: REDACTED, host id: REDACTED/TgW8ggfHHH0/vzJFuXwh8fgk=
```

The build is successful but no logs are stored.

## Debugging Done

Here are some steps I have used to debug to rule out permission issues.

1. All three buckets exist
2. The RBAC role that builder-controller is using is pointing to the correct IAM role
3. The service account that the builder-controller is using is bound to the correct RBAC role and permissions
4. The AWS IAM role give builder-controller full admin perms on all of s3

## Versions

- ghcr.io/jenkins-x/jx-build-controller:0.3.15
- EKS v1.21.9-eks-0d102a7

## jx-reqirements

```
apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://jenkins-x-chartmuseum.jx.svc.cluster.local:8080
    clusterName: REDACTED
    devEnvApprovers:
    - todo
    environmentGitOwner: REDACTED
    gitKind: gitlab
    gitName: gl
    gitServer: https://gitlab.com
    project: "REDACTED"
    provider: eks
    region: us-west-2
    registry: REDACTED.dkr.ecr.us-east-2.amazonaws.com
  environments:
  - key: dev
    owner: REDACTED
    repository: REDACTED
  - key: staging
  - key: production
  ingress:
    domain: REDACTED.REDACTED.com
    externalDNS: true
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: REDACTED
      enabled: true
      production: true
  pipelineUser:
    username: REDACTED
  repository: nexus
  secretStorage: secretsManager
  storage:
  - name: logs
    url: s3://logs-REDACTED-dev-eks-20220420182851392800000001
  - name: reports
    url: s3://reports-REDACTED-dev-eks-20220420182851770800000006
  - name: repository
    url: s3://repository-REDACTED-dev-eks-20220420182851398900000002
  terraform: true
  vault: {}
  webhook: lighthouse
```

## Questions

1. How do I debug more?
2. What process is actually writing the logs?  Is there another pod that is missing the IAM token?  I know we have moved from ClusterRoles to Roles recently

## TLDR;

The s3 buckets exist, the build runs, no logs are saved, and we cannot see any logs in the dashboard.
